### ISSUE TITLE
TinyMCE pages scroll down then back up on load

### ISSUE THREAD

**Issue by kvablack** [lasa/website#8]
As of version 4, when TinyMCE finishes loading, it steals focus and then scrolls down the browser window to the very bottom of the editor area. Unfortunately, there seems to be no way to turn this off, so I attempted to fix it in 64a1a97 by waiting until TinyMCE finishes loading and then immediately scrolling back up and focusing the first element of the form. However, this causes the page to very quickly jump down then back up when it first loads.

**Comment by kvablack** [comment]
After some debugging, I've traced the issue down to [this JavaScript function](https://github.com/lasa/website/blob/64a1a97f0bcd082eb3409c364ae38ed808385847/app/utils.py#L40-L44). In order to set 11pt as the default font in the TinyMCE toolbar, execCommand has to be called on the editor after it initializes. It seems that this call causes the page to scroll down until the top of the screen is in line with the top of the editor. 

I think having 11pt clearly be the default font is better for user experience than preventing the short flicker caused by the scroll, so I'm going to leave it as it is until a better solution can be found.

**Comment by oja** [comment]
How big is 11pt compared to what people use "regularly"?

**Comment by kvablack** [comment]
http://reeddesign.co.uk/test/points-pixels.html

11pt is about 15px, which is really close to the 14px we're using as the default for the rest of the website. That's not really the point, though— the issue arises from the fact that I'm trying to emulate the behavior of a standard text editor where the font size select dropdown menu starts on the default value. Evidently, I can't do that without causing the scrolling problem, so I submitted an issue to the TinyMCE repository.

**Comment by oja** [comment]
Maybe we should be submoduling TinyMCE...

https://github.com/lasa/tinymce
